version: "3.9"
name: "keycloak"

services:
  # https://www.keycloak.org/server/containers
  keycloak:
    container_name: keycloak-${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile    
    hostname:  keycloak-${IMAGE_VERSION}
    image: quay.io/keycloak/keycloak:${IMAGE_VERSION}
    working_dir: /opt/keycloak
    ports:
      - ${KEYCLOAK_LISTEN_PORT}:8443
    volumes:
      - ./import/:/opt/keycloak/data/import
      # optional, ssl certs
      - ./certs/:/etc/x509/https
    environment:
      UPSTREAM_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
      KEYCLOAK_LISTEN_PORT: ${KEYCLOAK_LISTEN_PORT}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_HOSTNAME: ${HOSTNAME}
      IMAGE_VERSION: ${IMAGE_VERSION}
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME: ${HOSTNAME}
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: "https://${HOSTNAME}:${KEYCLOAK_LISTEN_PORT}"
      KC_HTTPS_PORT: ${KEYCLOAK_LISTEN_PORT}
    command: 
      # dev
      - start-dev 
      - --import-realm
      - --hostname=${HOSTNAME}
      - --hostname-port=${KEYCLOAK_LISTEN_PORT}
      #- --https-certificate-file=/etc/x509/https/tls.crt
      #- --https-certificate-key-file=/etc/x509/https/tls.key
      # prod
      # - start --optimized
      # - --hostname-port=${KEYCLOAK_LISTEN_PORT}
      #- --https-certificate-file=/etc/x509/https/tls.crt
      #- --https-certificate-key-file=/etc/x509/https/tls.key
      

