version: "3.9"
name: "nginx"

services:
  nginx:
    image: nginx
    volumes: 
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/conf.d:/etc/nginx/conf.d:ro
    - ./html:/usr/share/nginx/html
    ports:
    - "${PORT}:80"
    environment:
    # - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    - NGINX_ENTRYPOINT_QUIET_LOGS=${NGINX_ENTRYPOINT_QUIET_LOGS}